location / {
    # try to serve file directly, fallback to rewrite
    try_files $uri $uri/ /index.php?$query_string;
}

location ~ ^/index\.php(/|$) {
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param HTTPS on;
    # Avoids https loops, not necessary,
    # but recommended for any client using a custom certificate:
    # fastcgi_param HTTPS off;
    # HTTP headers removed for security
    fastcgi_param SERVER_NAME $host;
}

# Deny access to .htaccess files
location ~ /\.ht {
    deny all;
}
